### ISSUE TITLE
Service url shown in output does not include port

### ISSUE THREAD

**Issue by neeraj-ec** [AlexandreBrg/openfga-helm#6]
One other small issue I faced, after helm deployment, in result message it shows the url of service where you can internally connect to openfga. Like 
```
You can connect to openfga at: 
openfga.ec-dev.svc.cluster.local
``` 
This message does not include the port. In reality the service is unreachable at that url without including the port, which is by default 8080. So I was able to connect the service at url 
```
openfga.ec-dev.svc.cluster.local:8080
```
Took me sometime and debugging to figure it out why my service was not able to connect openfga at that url.

_Originally posted by @neeraj-ec in https://github.com/AlexandreBrg/openfga-helm/issues/4#issuecomment-1312343582_

**Comment by alexandrebrg** [comment]
Hi @neeraj-ec, thank you for the feedback :)

On my side, when doing the release, I have the below message. 

```
OpenFGA can be accessed through the following DNS name from within your cluster:

    authz-openfga.default.svc.cluster.local (port 8080)
```

Instead of having the port between parenthesis, it would make sense to have it in standard format instead (`$service:$port`). It would make it more intuitive. If you want, you can do a PR for that, the message is created in the file `./openfga/templates/NOTES.txt`.
